name: varcompress
description: Some 'algorithm' to compress files like a zip file but 'better'
version: 1.0.0
homepage: https://github.com/TheHackerCoding/varcompress
repository: https://github.com/TheHackerCoding/varcompress

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.7.0
  async: ^2.4.2
  cryptoutils: ^0.4.0
  logger: ^0.9.4


dev_dependencies:
  pedantic: ^1.9.0
